fObj=open(r"C:\Users\vaska\OneDrive\Desktop\Python\File handling files\File.xls","w")
fObj.write("Roll no.")
fObj.write("\tName")
fObj.write("\tAge")
fObj.write("\n1")
fObj.write("\tRam")
fObj.write("\t23")
fObj.write("\n2")
fObj.write("\tVasu")
fObj.write("\t68")
fObj.close()
print("file created")
